let currentPage = 0;

const totalPages = 18;

const STORAGE_PREFIX = 'calisthenics_';


/*
|--------------------------------------------------------------------------
| PAGE NAVIGATION
|--------------------------------------------------------------------------
*/

function updatePage() {

    const pages = document.querySelectorAll('.print-page');
    const navLinks = document.querySelectorAll('.nav-link');

    pages.forEach((page, index) => {

        if (index === currentPage) {
            page.classList.add('active');
        } else {
            page.classList.remove('active');
        }

    });


    navLinks.forEach(link => {

        const pageIndex = Number(link.dataset.page);

        if (pageIndex === currentPage) {
            link.classList.add('active');
        } else {
            link.classList.remove('active');
        }

    });


    document.getElementById('pageIndicator').innerText =
        `Page ${currentPage + 1} of ${totalPages}`;


    document.getElementById('prevBtn').disabled =
        currentPage === 0;

    document.getElementById('nextBtn').disabled =
        currentPage === totalPages - 1;

}


/*
|--------------------------------------------------------------------------
| NAVIGATION FUNCTIONS
|--------------------------------------------------------------------------
*/

function nextPage() {

    if (currentPage < totalPages - 1) {

        currentPage++;

        updatePage();

    }

}


function prevPage() {

    if (currentPage > 0) {

        currentPage--;

        updatePage();

    }

}


function goToPage(index) {

    if (index < 0 || index >= totalPages) {
        return;
    }

    currentPage = index;

    updatePage();

}


/*
|--------------------------------------------------------------------------
| MARKDOWN LOADING
|--------------------------------------------------------------------------
*/

async function loadMarkdownPages() {

    const pages = document.querySelectorAll('.markdown-page');

    for (const page of pages) {

        const path = page.dataset.markdown;

        if (!path) {
            continue;
        }

        try {

            const response = await fetch(path);

            if (!response.ok) {
                throw new Error(
                    `HTTP ${response.status}: ${response.statusText}`
                );
            }

            const markdown = await response.text();

            page.innerHTML = `
                <div class="page-main-content markdown-content">
                    ${marked.parse(markdown)}
                </div>
            `;

            convertMarkdownCheckboxes(page);

        } catch (error) {

            console.error(`Unable to load ${path}`, error);

            page.innerHTML = `
                <div class="page-main-content">
                    <h2>Unable to Load Content</h2>

                    <div class="callout">
                        <p>
                            The content file could not be loaded.
                        </p>

                        <p>
                            <strong>File:</strong> ${path}
                        </p>

                        <p>
                            Make sure the Markdown file exists in the
                            repository and that GitHub Pages is serving
                            the project from the correct directory.
                        </p>
                    </div>
                </div>
            `;

        }

    }

}


/*
|--------------------------------------------------------------------------
| CONVERT MARKDOWN CHECKBOXES
|--------------------------------------------------------------------------
|
| Markdown checkboxes generated by marked.js are converted into the
| same visual structure used by the original application.
|
*/

function convertMarkdownCheckboxes(page) {

    const checkboxItems = page.querySelectorAll(
        'input[type="checkbox"]'
    );

    checkboxItems.forEach((checkbox, index) => {

        /*
         * Give every checkbox a permanent ID.
         *
         * If the Markdown file has:
         *
         * - [ ] Some milestone
         *
         * marked.js creates the checkbox but doesn't necessarily
         * provide the ID we need for localStorage.
         */

        const listItem = checkbox.closest('li');

        let identifier = '';

        if (listItem) {

            const labelText = listItem.textContent
                .replace(/\s+/g, ' ')
                .trim()
                .toLowerCase();

            identifier = labelText
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-|-$/g, '');

        }

        const fileName = page.dataset.markdown
            .split('/')
            .pop()
            .replace('.md', '');

        checkbox.id =
            `${STORAGE_PREFIX}${fileName}-${identifier || index}`;

        checkbox.classList.add('markdown-checkbox');

        checkbox.addEventListener(
            'change',
            saveProgress
        );

        /*
         * Turn the parent list item into the visual checklist
         * component.
         */

        if (listItem) {

            listItem.classList.add('checklist-item');

            /*
             * Remove the browser-generated task-list styling
             * while retaining the actual checkbox.
             */

            listItem.style.listStyle = 'none';

        }

    });


    loadProgress();

}


/*
|--------------------------------------------------------------------------
| PROGRESS STORAGE
|--------------------------------------------------------------------------
*/

function getAllProgressCheckboxes() {

    return document.querySelectorAll(
        'input[type="checkbox"]'
    );

}


function saveProgress() {

    const checkboxes =
        getAllProgressCheckboxes();


    checkboxes.forEach(checkbox => {

        if (!checkbox.id) {
            return;
        }

        localStorage.setItem(
            checkbox.id,
            checkbox.checked
        );

    });

}


function loadProgress() {

    const checkboxes =
        getAllProgressCheckboxes();


    checkboxes.forEach(checkbox => {

        if (!checkbox.id) {
            return;
        }

        const savedState =
            localStorage.getItem(checkbox.id);


        if (savedState !== null) {

            checkbox.checked =
                savedState === 'true';

        }

    });

}


/*
|--------------------------------------------------------------------------
| SIDEBAR EVENTS
|--------------------------------------------------------------------------
*/

function initializeNavigation() {

    const navLinks =
        document.querySelectorAll('.nav-link');


    navLinks.forEach(link => {

        link.addEventListener('click', () => {

            const page =
                Number(link.dataset.page);

            goToPage(page);

        });

    });

}


/*
|--------------------------------------------------------------------------
| SLIDER BUTTON EVENTS
|--------------------------------------------------------------------------
*/

function initializeControls() {

    document
        .getElementById('prevBtn')
        .addEventListener('click', prevPage);


    document
        .getElementById('nextBtn')
        .addEventListener('click', nextPage);

}


/*
|--------------------------------------------------------------------------
| KEYBOARD NAVIGATION
|--------------------------------------------------------------------------
*/

function initializeKeyboardNavigation() {

    document.addEventListener('keydown', event => {

        /*
         * Don't hijack keyboard navigation when the user is
         * interacting with a checkbox or another form element.
         */

        if (
            event.target.tagName === 'INPUT' ||
            event.target.tagName === 'TEXTAREA' ||
            event.target.tagName === 'SELECT'
        ) {
            return;
        }


        if (event.key === 'ArrowRight') {
            nextPage();
        }


        if (event.key === 'ArrowLeft') {
            prevPage();
        }

    });

}


/*
|--------------------------------------------------------------------------
| INITIALIZATION
|--------------------------------------------------------------------------
*/

async function initializeApp() {

    initializeNavigation();

    initializeControls();

    initializeKeyboardNavigation();

    updatePage();

    /*
     * Load the external Markdown files.
     */

    await loadMarkdownPages();

    /*
     * Load any existing saved checkbox states.
     */

    loadProgress();

}


document.addEventListener(
    'DOMContentLoaded',
    initializeApp
);